/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { approveReturnGame } from '../fn/game/approve-return-game';
import { ApproveReturnGame$Params } from '../fn/game/approve-return-game';
import { borrowGame } from '../fn/game/borrow-game';
import { BorrowGame$Params } from '../fn/game/borrow-game';
import { findAllBorrowedGames } from '../fn/game/find-all-borrowed-games';
import { FindAllBorrowedGames$Params } from '../fn/game/find-all-borrowed-games';
import { findAllGames } from '../fn/game/find-all-games';
import { FindAllGames$Params } from '../fn/game/find-all-games';
import { findAllGamesByOwner } from '../fn/game/find-all-games-by-owner';
import { FindAllGamesByOwner$Params } from '../fn/game/find-all-games-by-owner';
import { findAllReturnedGames } from '../fn/game/find-all-returned-games';
import { FindAllReturnedGames$Params } from '../fn/game/find-all-returned-games';
import { findGameById } from '../fn/game/find-game-by-id';
import { FindGameById$Params } from '../fn/game/find-game-by-id';
import { GameResponse } from '../models/game-response';
import { PageResponseBorrowedGameResponse } from '../models/page-response-borrowed-game-response';
import { PageResponseGameResponse } from '../models/page-response-game-response';
import { returnGame } from '../fn/game/return-game';
import { ReturnGame$Params } from '../fn/game/return-game';
import { saveGame } from '../fn/game/save-game';
import { SaveGame$Params } from '../fn/game/save-game';
import { updateGameStatus } from '../fn/game/update-game-status';
import { UpdateGameStatus$Params } from '../fn/game/update-game-status';
import { uploadGameImage } from '../fn/game/upload-game-image';
import { UploadGameImage$Params } from '../fn/game/upload-game-image';

@Injectable({ providedIn: 'root' })
export class GameService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `findAllGames()` */
  static readonly FindAllGamesPath = '/games';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllGames()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllGames$Response(params?: FindAllGames$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseGameResponse>> {
    return findAllGames(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllGames$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllGames(params?: FindAllGames$Params, context?: HttpContext): Observable<PageResponseGameResponse> {
    return this.findAllGames$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseGameResponse>): PageResponseGameResponse => r.body)
    );
  }

  /** Path part for operation `saveGame()` */
  static readonly SaveGamePath = '/games';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `saveGame()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveGame$Response(params: SaveGame$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return saveGame(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `saveGame$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveGame(params: SaveGame$Params, context?: HttpContext): Observable<number> {
    return this.saveGame$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `uploadGameImage()` */
  static readonly UploadGameImagePath = '/games/image/{game-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `uploadGameImage()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  uploadGameImage$Response(params: UploadGameImage$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return uploadGameImage(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `uploadGameImage$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  uploadGameImage(params: UploadGameImage$Params, context?: HttpContext): Observable<{
}> {
    return this.uploadGameImage$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `borrowGame()` */
  static readonly BorrowGamePath = '/games/borrow/{game-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `borrowGame()` instead.
   *
   * This method doesn't expect any request body.
   */
  borrowGame$Response(params: BorrowGame$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return borrowGame(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `borrowGame$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  borrowGame(params: BorrowGame$Params, context?: HttpContext): Observable<number> {
    return this.borrowGame$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `updateGameStatus()` */
  static readonly UpdateGameStatusPath = '/games/shareable/{game-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateGameStatus()` instead.
   *
   * This method doesn't expect any request body.
   */
  updateGameStatus$Response(params: UpdateGameStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return updateGameStatus(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateGameStatus$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  updateGameStatus(params: UpdateGameStatus$Params, context?: HttpContext): Observable<number> {
    return this.updateGameStatus$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `returnGame()` */
  static readonly ReturnGamePath = '/games/borrow/return/{game-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `returnGame()` instead.
   *
   * This method doesn't expect any request body.
   */
  returnGame$Response(params: ReturnGame$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return returnGame(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `returnGame$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  returnGame(params: ReturnGame$Params, context?: HttpContext): Observable<number> {
    return this.returnGame$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `approveReturnGame()` */
  static readonly ApproveReturnGamePath = '/games/borrow/return/approve/{game-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `approveReturnGame()` instead.
   *
   * This method doesn't expect any request body.
   */
  approveReturnGame$Response(params: ApproveReturnGame$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return approveReturnGame(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `approveReturnGame$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  approveReturnGame(params: ApproveReturnGame$Params, context?: HttpContext): Observable<number> {
    return this.approveReturnGame$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `findGameById()` */
  static readonly FindGameByIdPath = '/games/{game-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findGameById()` instead.
   *
   * This method doesn't expect any request body.
   */
  findGameById$Response(params: FindGameById$Params, context?: HttpContext): Observable<StrictHttpResponse<GameResponse>> {
    return findGameById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findGameById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findGameById(params: FindGameById$Params, context?: HttpContext): Observable<GameResponse> {
    return this.findGameById$Response(params, context).pipe(
      map((r: StrictHttpResponse<GameResponse>): GameResponse => r.body)
    );
  }

  /** Path part for operation `findAllReturnedGames()` */
  static readonly FindAllReturnedGamesPath = '/games/returned';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllReturnedGames()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllReturnedGames$Response(params?: FindAllReturnedGames$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseBorrowedGameResponse>> {
    return findAllReturnedGames(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllReturnedGames$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllReturnedGames(params?: FindAllReturnedGames$Params, context?: HttpContext): Observable<PageResponseBorrowedGameResponse> {
    return this.findAllReturnedGames$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseBorrowedGameResponse>): PageResponseBorrowedGameResponse => r.body)
    );
  }

  /** Path part for operation `findAllGamesByOwner()` */
  static readonly FindAllGamesByOwnerPath = '/games/owner';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllGamesByOwner()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllGamesByOwner$Response(params?: FindAllGamesByOwner$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseGameResponse>> {
    return findAllGamesByOwner(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllGamesByOwner$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllGamesByOwner(params?: FindAllGamesByOwner$Params, context?: HttpContext): Observable<PageResponseGameResponse> {
    return this.findAllGamesByOwner$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseGameResponse>): PageResponseGameResponse => r.body)
    );
  }

  /** Path part for operation `findAllBorrowedGames()` */
  static readonly FindAllBorrowedGamesPath = '/games/borrowed';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllBorrowedGames()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllBorrowedGames$Response(params?: FindAllBorrowedGames$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseBorrowedGameResponse>> {
    return findAllBorrowedGames(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllBorrowedGames$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllBorrowedGames(params?: FindAllBorrowedGames$Params, context?: HttpContext): Observable<PageResponseBorrowedGameResponse> {
    return this.findAllBorrowedGames$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseBorrowedGameResponse>): PageResponseBorrowedGameResponse => r.body)
    );
  }

}
