/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { AuthenticationRequest } from './models/authentication-request';
export { AuthenticationResponse } from './models/authentication-response';
export { BorrowedGameResponse } from './models/borrowed-game-response';
export { Feedback } from './models/feedback';
export { FeedbackRequest } from './models/feedback-request';
export { FeedbackResponse } from './models/feedback-response';
export { Game } from './models/game';
export { GameCategories } from './models/game-categories';
export { GameRequest } from './models/game-request';
export { GameResponse } from './models/game-response';
export { GameTrack } from './models/game-track';
export { GrantedAuthority } from './models/granted-authority';
export { PageResponseBorrowedGameResponse } from './models/page-response-borrowed-game-response';
export { PageResponseFeedbackResponse } from './models/page-response-feedback-response';
export { PageResponseGameResponse } from './models/page-response-game-response';
export { RegistrationRequest } from './models/registration-request';
export { Role } from './models/role';
export { User } from './models/user';
