/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BorrowedGameResponse {
  description?: string;
  id?: number;
  name?: string;
  rate?: number;
  returnApproved?: boolean;
  returned?: boolean;
}
