/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Game } from '../models/game';
export interface Feedback {
  createdBy?: number;
  creationDate?: string;
  game?: Game;
  id?: number;
  lastUpdateBy?: number;
  lastUpdateDate?: string;
  message?: string;
  note?: number;
}
