/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GameCategories } from './game-categories';
export interface GameRequest {
  age: number;
  categories?: Array<GameCategories>;
  description: string;
  gameDesigner?: string;
  gameVersion?: string;
  id?: number;
  maxPlayers?: number;
  minPlayers?: number;
  name: string;
  playingTime?: number;
  shareable?: boolean;
  yearPublished?: string;
}
