/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Game } from './game';
import { User } from './user';
export interface GameTrack {
  createdBy?: number;
  creationDate?: string;
  game?: Game;
  id?: number;
  lastUpdateBy?: number;
  lastUpdateDate?: string;
  returnApproved?: boolean;
  returned?: boolean;
  user?: User;
}
