/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Game } from './game';
export interface GameCategories {
  category?: string;
  games?: Array<Game>;
  id?: number;
}
