/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GameCategories } from './game-categories';
export interface GameResponse {
  age?: number;
  categories?: Array<GameCategories>;
  description?: string;
  gameDesigner?: string;
  gameVersion?: string;
  id?: number;
  image?: Array<string>;
  maxPlayers?: number;
  minPlayers?: number;
  name?: string;
  owner?: string;
  playingTime?: number;
  rate?: number;
  shareable?: boolean;
  yearPublished?: string;
}
