/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BorrowedGameResponse } from './borrowed-game-response';
export interface PageResponseBorrowedGameResponse {
  data?: Array<BorrowedGameResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
