/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Game } from './game';
import { GameTrack } from './game-track';
import { GrantedAuthority } from './granted-authority';
import { Role } from './role';
export interface User {
  accountLocked?: boolean;
  accountNonExpired?: boolean;
  accountNonLocked?: boolean;
  authorities?: Array<GrantedAuthority>;
  createdAt?: string;
  credentialsNonExpired?: boolean;
  dateOfBirth?: string;
  email?: string;
  enabled?: boolean;
  firstName?: string;
  fullName?: string;
  games?: Array<Game>;
  id?: number;
  lastName?: string;
  name?: string;
  password?: string;
  roles?: Array<Role>;
  transactions?: Array<GameTrack>;
  updatedAt?: string;
  username?: string;
}
